name: Setup

description: Sets up the repo for a typical CI job

inputs:
  cache:
    description: Cache the pnpm store
    default: true
    required: false
  install-flags:
    description: Flags to pass to `pnpm install`
    required: false
    type: string
  node-version:
    description: Node.js version to use
    default: '24'
    required: false

runs:
  steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
      with:
        cache: ${{ inputs.cache }}
        install: ${{ inputs.install-flags == '' }}
        runtime: node@${{ inputs.node-version }}

    - run: pnpm install ${{ inputs.install-flags }}
      if: ${{ inputs.install-flags != '' }}
      shell: bash
  using: composite
