export type { Result } from "./Result.ts";
export { validate } from "./validate.ts";
export {
	validateAuthor,
	validateBin,
	validateBrowser,
	validateBugs,
	validateBundleDependencies,
	validateConfig,
	validateContributors,
	validateCpu,
	validateDependencies,
	validateDescription,
	validateDependencies as validateDevDependencies,
	validateDevEngines,
	validateDirectories,
	validateEngines,
	validateExports,
	validateFiles,
	validateFunding,
	validateGypfile,
	validateHomepage,
	validateKeywords,
	validateLicense,
	validateMain,
	validateMan,
	validateName,
	validateDependencies as validateOptionalDependencies,
	validateOs,
	validatePackageManager,
	validateDependencies as validatePeerDependencies,
	validatePrivate,
	validatePublishConfig,
	validateRepository,
	validateScripts,
	validateSideEffects,
	validateType,
	validateVersion,
	validateWorkspaces,
} from "./validators/index.ts";
