export type { Result } from "./Result.ts";
export { validate } from "./validate.ts";
export {
	validateAuthor,
	validateBin,
	validateBundleDependencies,
	validateConfig,
	validateContributors,
	validateCpu,
	validateDependencies,
	validateDescription,
	validateDependencies as validateDevDependencies,
	validateDirectories,
	validateEngines,
	validateExports,
	validateFiles,
	validateHomepage,
	validateKeywords,
	validateLicense,
	validateMain,
	validateMan,
	validateName,
	validateDependencies as validateOptionalDependencies,
	validateOs,
	validatePackageManager,
	validateDependencies as validatePeerDependencies,
	validatePrivate,
	validatePublishConfig,
	validateRepository,
	validateScripts,
	validateSideEffects,
	validateType,
	validateVersion,
	validateWorkspaces,
} from "./validators/index.ts";
