export type { Result } from './Result.ts';
// eslint-disable-next-line @typescript-eslint/no-deprecated
export { validate } from './validate.ts';
export type { ValidateFunction } from './validate.types.ts';
export {
  validateAuthor,
  validateBin,
  validateBrowser,
  validateBugs,
  validateBundleDependencies,
  validateConfig,
  validateContributors,
  validateCpu,
  validateDependencies,
  validateDescription,
  validateDependencies as validateDevDependencies,
  validateDevEngines,
  validateDirectories,
  validateEngines,
  validateExports,
  validateFiles,
  validateFunding,
  validateGypfile,
  validateHomepage,
  validateKeywords,
  validateLibc,
  validateLicense,
  validateMain,
  validateMan,
  validateName,
  validateDependencies as validateOptionalDependencies,
  validateOs,
  validatePackageManager,
  validateDependencies as validatePeerDependencies,
  validatePeerDependenciesMeta,
  validatePrivate,
  validatePublishConfig,
  validateRepository,
  validateScripts,
  validateSideEffects,
  validateType,
  validateVersion,
  validateWorkspaces,
  type ValidateDependenciesOptions,
} from './validators/index.ts';
