name: CI

on:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  # Gatekeeper job to ensure that if ci ran because of a label event, we're only running if the label is "ci"
  check_trigger:
    name: Check Trigger
    if: github.event.action != 'labeled' || github.event.label.name == 'ci'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger condition met, proceeding with CI..."

  # Actual CI jobs
  build:
    name: Build
    needs: check_trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: node lib/index.mjs

  dedupe_check:
    name: Dedupe Check
    needs: check_trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm dedupe --check --prefer-offline

  lint:
    name: Lint
    needs: check_trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: pnpm lint

  lint_knip:
    name: Lint Knip
    needs: check_trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm lint:knip

  prettier:
    name: Prettier
    needs: check_trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm format --list-different

  test:
    name: Test
    needs: check_trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - uses: codecov/codecov-action@v5
        if: always()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  type_check:
    name: Type Check
    needs: check_trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: ./.github/actions/prepare
      - run: pnpm typecheck
