name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm build
      - run: node dist/index.mjs

  dedupe_check:
    name: Dedupe Check
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm dedupe --check --prefer-offline

  engines_check:
    name: Engines Check (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22.13.0
          - 22
          - 24.0.0
          - 24
          - 26
    steps:
      - uses: $/.github/actions/setup
        with:
          install-flags: '--prod --engine-strict --ignore-scripts'
          node-version: ${{ matrix.node-version }}

  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm format --list-different

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm build
      - run: pnpm lint

  lint_knip:
    name: Lint Knip
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm lint:knip

  test_node:
    name: Test (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 22.13.0
          - 22
          - 24.0.0
          - 24
          - 26
    steps:
      - uses: $/.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm test run

  test_os:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm run test --coverage
      - uses: codecov/codecov-action@v5
        if: success() && (matrix.os == 'ubuntu-latest')
        with:
          fail_ci_if_error: true
          use_oidc: true

  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: $/.github/actions/setup
      - run: pnpm typecheck
