name: Label Trigger

on:
  pull_request:
    types: [labeled]

jobs:
  label-filter:
    if: github.event.label.name == 'ci'
    runs-on: ubuntu-latest
    steps:
      - name: Create Token
        id: create_token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.FAITHBOT_APP_CLIENT_ID }}
          private-key: ${{ secrets.FAITHBOT_APP_PRIVATE_KEY }}

      - name: Trigger CI
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ steps.create_token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://github.com{{ github.repository }}/dispatches \
            -d '{"event_type": "run-ci", "client_payload": {"pr_number": "${{ github.event.pull_request.number }}", "sha": "${{ github.event.pull_request.head.sha }}"}}'
